# Generated by Django 5.1.2 on 2025-11-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='newone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100, unique=True)),
                ('ral_date', models.CharField(max_length=100)),
                ('budget', models.CharField(max_length=100)),
                ('rating', models.IntegerField(max_length=100)),
            ],
        ),
    ]
