# Generated by Django 5.1.2 on 2025-11-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siva_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newone',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
