# Generated by Django 5.1.2 on 2025-11-27 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siva_app', '0002_alter_newone_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameuser', models.CharField(max_length=100, unique=True)),
                ('phonenumber', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
